Remove non used dirs and logrotate rules
OpenObservatory/lepidopter-update pull request #8
Opened 2016-09-14 18:42 UTC by anadahz

2016-09-14 18:43 UTC, anadahz commented
The update should also be signed.

2016-09-14 19:27 UTC, anadahz commented
I made the required changes to ooniprobe WUI port.

2016-09-14 21:32 UTC, hellais commented on updater/versions/update-1.py
> +def write_lepidopter_update_logrotate():
This function is called like the function above.

2016-09-14 21:33 UTC, hellais commented on updater/versions/update-1.py
> +def write_lepidopter_update_logrotate():
You then actually need to call the function in the perform_update part of the script.

2016-09-14 21:33 UTC, hellais requested changes
Fix function call

2016-09-15 10:45 UTC, hellais approved these changes

2016-09-15 10:45 UTC, hellais commented
I pushed a fix for this, merging.

2016-09-15 10:45 UTC, merged